name: Generate Installable Plugin, and Upload as Release Asset
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
    - uses: actions/checkout@v2    
    - name: Build project
      run: |
        composer install --no-dev --optimize-autoloader
        mkdir build        
    - name: Create artifact
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -X -r build/wetory-support.zip . -x *.git* node_modules/\* .* "*/\.*" *.dist composer.* build**     
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: wetory-support
        path: build/wetory-support.zip        
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: build/wetory-support.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
